FROM python:3.13

WORKDIR /app

# include compiler
COPY include/kommando kommando
# include libs
COPY include/kdolib/ kdolib/
# include runner
COPY runner.py runner.py

RUN useradd -m appuser && chown -R appuser /app
USER appuser

# communication port
EXPOSE 7878

ENV PATH "$PATH:/home/appuser/.local/bin"
ENV TMPDIR "/sandbox"

RUN pip install flask apscheduler wonderwords gunicorn

CMD [ "gunicorn", "--preload", "--worker-temp-dir", "/sandbox", " --bind", "0.0.0.0:7878", "runner:app"]