#!/bin/sh

# Note that this is order dependant: 
# you need to register ::foo before registring ::foo::bar

echo ::c_api=kdolib/c_api/c_api.kdo \
     ::c_api::str=kdolib/c_api/str.kdo \
     ::c_api::math=kdolib/c_api/math.kdo \
     ::std=kdolib/std/std.kdo \
     ::std::mem=kdolib/std/mem.kdo \
     ::std::vec=kdolib/std/vec.kdo \
     ::std::io=kdolib/std/io.kdo