[book]
authors = ["dragoÏ€"]
language = "en"
multilingual = false
src = "src"
title = "Kommando Docs"

[output.html]
mathjax-support = true
default-theme = "ayu"
preferred-dark-theme = "ayu"

[output.html.code.hidelines]
rs = "!"
c = "!"

[output.html.fold]
enable = true