[book]
authors = ["dragoÏ€"]
language = "en"
multilingual = false
src = "src"
title = "Kommando Docs"

[output.html]
mathjax-support = true

[output.html.code.hidelines]
rs = "!"

[output.html.fold]
enable = true